baseurl: "https://bldavies.com/"
blackfriday:
  fractions: false
disableKinds: ["taxonomyTerm", "sitemap"]
footnotereturnlinkcontents: "â†©"
frontmatter:
  date: [":filename", ":default"]
ignoreFiles: ["\\.aux$", "\\.log$", "\\.out$", "\\.RData$", "\\.rds$", "\\.Rmd$", "\\.tex$"]
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home: ["HTML", "RSS"]
  section: ["HTML"]
params:
  author: Benjamin Davies
  description: "Ben is an economics PhD candidate at Stanford University. His research uses theoretical and empirical tools to study how people learn and interact."
  githubContentURL: "https://github.com/bldavies/bldavies.com/tree/master/content/"
  orcidURL: https://orcid.org/0000-0002-1749-4567
  repecURL: https://ideas.repec.org/f/pda777.html
  scopusURL: https://www.scopus.com/authid/detail.uri?authorId=57218922178
  scholarURL: https://scholar.google.com/citations?user=iet9PyAAAAAJ
permalinks:
  blog: "/blog/:slug/"
pygmentsCodeFences: true
pygmentsUseClasses: true
taxonomies:
  topic: topics
title: Ben Davies
