baseurl: "https://bldavies.com/"
blackfriday:
  fractions: false
disableKinds: ["taxonomy", "taxonomyTerm", "sitemap"]
footnotereturnlinkcontents: "â†©"
frontmatter:
  date: [":filename", ":default"]
googleAnalytics: UA-123726505-4
ignoreFiles: ["\\.log$", "\\.RData$", "\\.rds$", "\\.Rmd$"]
outputs:
  home: ["HTML"]
params:
  author: Benjamin Davies
  email: ben.davies@motu.org.nz
  githubContentURL: "https://github.com/bldavies/bldavies.com/tree/master/content/"
  repec: https://ideas.repec.org/f/pda777
  scholar: https://scholar.google.co.nz/citations?user=iet9PyAAAAAJ
  orcid: https://orcid.org/0000-0002-1749-4567
permalinks:
  blog: "/blog/:slug/"
pygmentsCodeFences: true
pygmentsUseClasses: true
title: Ben Davies
