baseurl: "https://bldavies.com/"
blackfriday:
  fractions: false
disableKinds: ["taxonomy", "taxonomyTerm", "sitemap"]
footnotereturnlinkcontents: "â†©"
frontmatter:
  date: [":filename", ":default"]
googleAnalytics: UA-123726505-4
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
params:
  author: Benjamin Davies
  email: ben.davies@motu.org.nz
  github: https://github.com/bldavies
  linkedin: https://www.linkedin.com/in/bl-davies/
  repec: https://ideas.repec.org/f/pda777
  scholar: https://scholar.google.co.nz/citations?user=iet9PyAAAAAJ
  orcid: https://orcid.org/0000-0002-1749-4567
pygmentsCodefences: true
pygmentsStyle: "pygments"
title: Ben Davies
